- name: Install Tomcat
  hosts: tomcat
  gather_facts: false
  become: true
  vars:
    tomcat_version: 8.5.23
    
    tomcat_permissions_production: True
    
    tomcat_users:
      - username: "tomcat"
        password: "welcome123"
        roles: "tomcat,admin,manager,manager-gui"
      - username: "opsadmin"
        password: "welcome123"
        roles: "tomcat"        
  roles:
    - role: tomcat-ansible-role
